#!/bin/sh
#
# Autor: Thyago Ismael
#
# Animeviewer - utilitário para o site animesonline.vip


#####################################################################
#####################################################################
## Arquivos de configuração. Altere se necessário
#
# Diretório base dos arquivos
DIR_CONFIG="$HOME/.config/animeviewer"
# Favoritos
ARQ_FAVORITOS="$DIR_CONFIG/favoritos"
# Diretório dos downloads
DIR_DOWNLOADS="$DIR_CONFIG/downloads"
# Lista de episodios a serem baixados
ARQ_FILA_DOWNLOAD="$DIR_DOWNLOADS/filaDownload"
# Arquivo de todos os links salvos
ARQ_LINKS="$DIR_CONFIG/links"
# Player de vídeo
PLAYER='mpv'

#####################################################################
#####################################################################
#####################################################################
#####################################################################

menuInicial()
{
    echo "Listão\nFavoritos\nDownloads\nAtualizar\nSair" | dmenu -i -p "Animeviewer "
}


criarArquivos()
{
    # Cria a pasta caso não exista
    test -d "$DIR_CONFIG" || mkdir -p "$DIR_CONFIG"

    # Cria a pasta de downloads
    test -d "$DIR_DOWNLOADS" || mkdir -p "$DIR_DOWNLOADS"

    # Arquivo de links
    test -f "$ARQ_LINKS" || touch "$ARQ_LINKS"

    # Arquivo de favoritos
    test -f "$ARQ_FAVORITOS" || touch "$ARQ_FAVORITOS"

    # Fila de donwload
    test -f "$ARQ_FILA_DOWNLOAD" || touch "$ARQ_FILA_DOWNLOAD"
}

#####################################################################
#####################################################################
#####################################################################
#####################################################################

atualizarLinks()
{
    MAIOR_PAGINA=189 # número de páginas do site (em 17-09-2019 haviam 189)

    getLinks $MAIOR_PAGINA

    notify-send Atualizado "$(wc -l $ARQ_LINKS | awk '{print $1}') animes salvos em $ARQ_LINKS"
}
# Remove a sintaxe do html deixando apenas a url e o nome
removerHTML()
{
    echo "$1" | sed 's/^.*href="// ; s/" [^"]*"/\t/ ; s/".*// ; s/ /_/g ; s/_Online//' | tr '\t' ' '
}

# Preenche o arquivo ARQ_LINKS
getLinks()
{
    TEMP=$(mktemp)  # Arquivo temporário para guardar links 

    for pagina in $(seq $1)
    do
        LINK="https://animesonline.vip/animes/"
        test $pagina -eq 1 || LINK="${LINK}page/$pagina/"

        # Baixa o HTML, procura o nome e o link correspondente e salva num arq temporario
        removerHTML "$(curl -s $LINK | grep '^<a itemp')" >> $TEMP

        # Porcentagem de animes listados
        PORCEN_ANIME=$(calc -dp $pagina / $1)
        echo "$PORCEN_ANIME"
        export PORCEN_ANIME
    done

    # Substitui o arquivo de links anterior pelo arquivo temporário ordenado
    sort -u $TEMP | sed '/^$/ d' > $ARQ_LINKS
    rm $TEMP # e remove-o
}

# Retorna a url da página do anime
selecionarAnime()
{
    dmenu -i -l 10 -p 'Escolha o título: ' < $1
}

# Retorna a url do episódio
selecionarEpisodio()
{
    # $1 é o link do anime
    test -z "$1" && exit 1 # caso não seja informado o nome

    EPISODIO=$(removerHTML "$(curl -s $1 | grep '^<a href=".*Epis')") # deixa apenas o link e o nome, nessa ordem

    if test -z "$EPISODIO"
    then
        notify-send -i error Erro "Não foi possível abrir o anime"
        exit 1
    fi
    echo "$EPISODIO" | dmenu -i -l 10 -p 'Escolha o episódio: ' | awk '{print $1}' # deixa apenas o link
}

menuAcaoEpisodio()
{
    # Pega o nome do anime
    ANIME=$(selecionarAnime $1) # $1 é o arquivo de links
    test -z "$ANIME" && return 
    # E usa pra pegar a url do episodio
    EPISODIO="$(selecionarEpisodio $(echo $ANIME | awk '{print $1}'))"
    test -z "$EPISODIO" && return 


    OPCOES="Reproduz
Baixar
Adicionar/Remover Favorito"

    ACAO=$(echo "$OPCOES" | dmenu -i -p 'O que fazer? ')
    case $ACAO in
        "Reproduzir")
            "$PLAYER" "$EPISODIO"
            ;;
        "Baixar")
            notify-send -i emblem-downloads "Download iniciado"
            baixarEpisodio $EPISODIO
            ;;
        "Adicionar/Remover Favorito")
            if grep "$ANIME" "$ARQ_FAVORITOS"
            then
                notify-send -i edittrash "Removido dos favoritos"
                grep -v "$ANIME" "$ARQ_FAVORITOS" | tee "$ARQ_FAVORITOS"
            else
                notify-send -i emblem-favorite "Adicionado aos favoritos"
                echo $ANIME >> $ARQ_FAVORITOS
            fi
            ;;
        *)
            ;;
    esac
}

baixarEpisodio()
{
    # Usa o nome do anime como diretorio
    NOME="$DIR_DOWNLOADS"/"$(echo $1 | sed 's|.*episodio/|| ; s|-epis.*|| ')"
    # Se não existir, cria
    test -d "$NOME" || mkdir "$NOME"

    youtube-dl -q $EPISODIO --exec "mv {} $NOME/" 2> /dev/null
    notify-send -i emblem-default "Download terminado"
}

#####################################################################
#####################################################################
#####################################################################
#####################################################################

criarArquivos

for i in $(seq 1)
do
    ESCOLHA="$(menuInicial)"

    case $ESCOLHA in
        "Listão")
            menuAcaoEpisodio "$ARQ_LINKS"
            ;;
        "Favoritos")
            menuAcaoEpisodio "$ARQ_FAVORITOS"
            ;;
        "Downloads")
            ;;
        "Atualizar")
            atualizarLinks
            ;;
        *)
            ;;
    esac
    test "$ESCOLHA" = "Sair" && break
done
