#!/bin/sh
#
# Autor: Thyago Ismael
#
# Animeviewer - utilitário para o site animesonline.vip


#####################################################################
#####################################################################
## Arquivos de configuração. Altere se necessário
#
# Diretório base dos arquivos
DIR_CONFIG="$HOME/.config/animeviewer"
# Diretório dos downloads
DIR_DOWNLOADS="$DIR_CONFIG/downloads"
# Arquivo de todos os links salvos
ARQ_LINKS="$DIR_CONFIG/links"
# Player de vídeo
PLAYER=mpv

#####################################################################
#####################################################################
#####################################################################
#####################################################################
criarArquivos()
{
    # Cria a pasta caso não exista
    test -d "$DIR_CONFIG" || mkdir -p "$DIR_CONFIG"

    # Cria a pasta de downloads
    test -d "$DIR_DOWNLOADS" || mkdir -p "$DIR_DOWNLOADS"

    # Cria o arquivo de links
    test -f "$ARQ_LINKS" || touch "$ARQ_LINKS"
}

removerHTML()
{
    echo "$1" | sed 's/^.*href="// ; s/" [^"]*"/\t/ ; s/".*// ; s/ /_/g ; s/_Online//' | tr '\t' ' '
}

getLinks()
{
    MAIOR_PAGINA=189 # número de páginas do site (em 17-09-2019 haviam 189)
    TEMP=$(mktemp)

    # Faz uma string com todos os links seguindo o formato definido no site
    LINKS="https://animesonline.vip/animes/"
    for pagina in $(seq 2 $MAIOR_PAGINA)
    do
        LINKS="$LINKS https://animesonline.vip/animes/page/$pagina/"
    done

    # Baixa todos nomes e os links de uma só vez para uma arquivo temporário
    removerHTML "$(curl -s $LINKS | grep '^<a itemp')" >> $TEMP

    # Substitui o arquivo de links anterior pelo arquivo temporário ordenado e remove-o
    sort -u $TEMP > $ARQ_LINKS
    rm $TEMP
    
    # Acabou
    echo -e "\n$(wc -l $ARQ_LINKS | cut -d' ' -f1) animes salvos"
}

selecionarAnime()
{
    # Mostra um menu com os nomes, depois busca o link relacionado
    grep "$(cut --fields 2 < $ARQ_LINKS  | dmenu -i -l 10 -p 'Escolha o título: ')" $ARQ_LINKS | awk '{print $1}' 
}

selecionarEpisodio()
{
    # $1 é o link do anime
   removerHTML "$(curl -s $1 | grep '^<a href=".*Epis')" | # deixa apenas o link e o nome, nessa ordem
   dmenu -i -l 10 -p 'Escolha o episódio: ' | awk '{print $1}' # deixa apenas o link
}

# Verifica se os arquivos e pastas necessárias existem
# Se não existirem, os cria
criarArquivos

# Menu inicial
ESCOLHA=$(echo -e 'Reproduzir\nBaixar\nAtualizar' | dmenu -i -p 'Animeviewer')

case $ESCOLHA in
    Reproduzir)
        selecionarEpisodio $(selecionarAnime) | xargs -rI{} $PLAYER {}
        ;;
    Baixar)
        ANIME="$(selecionarAnime)"
        DIR_ANIME=$(echo $ANIME | cut -d'/' -f4) # usa a ultima parte da url como nome da pasta

        # cria a pasta deste anime específico se não existir
        test -d "$DIR_DOWNLOADS/$DIR_ANIME" || mkdir -p "$DIR_DOWNLOADS/$DIR_ANIME" 

        URL_EPISODIO="$(selecionarEpisodio "$ANIME")"
        NOME_EPISODIO=$(echo $URL_EPISODIO | cut -d'/' -f 5) # ultima parte do url como nome do arquivo

        youtube-dl "$URL_EPISODIO" --exec "mv {} \"$DIR_DOWNLOADS/$DIR_ANIME/$NOME_EPISODIO\""
        ;;
    Atualizar)
        notify-send "Animeviewer atualizado" "$(getLinks)" # atualiza e manda notifição
        ;;
    *)
        exit 1
        ;;
esac
