#!/bin/sh
#
# Autor: Thyago Ismael
#
# Animeviewer - utilitário para o site animesonline.vip


#####################################################################
#####################################################################
## Arquivos de configuração. Altere se necessário
#
# Diretório base dos arquivos
DIR_CONFIG="$HOME/.config/animeviewer"
# Lista de episodios a serem baixados
ARQ_LISTA_PARA_BAIXAR="$DIR_DOWNLOADS/paraBaixar"
# Diretório dos downloads
DIR_DOWNLOADS="$DIR_CONFIG/downloads"
# Arquivo de todos os links salvos
ARQ_LINKS="$DIR_CONFIG/links"
# Player de vídeo
PLAYER='vlc'

#####################################################################
#####################################################################
#####################################################################
#####################################################################

menuInicial()
{
    OPCOES="Lista\nFavoritos\nDownloads\nAtualizar\nSair"
    echo "$OPCOES" | dmenu -i
}

menuAcaoEpisodio()
{
    OPCOES="Reproduzir
Baixar
Adicionar/Remover Favorito"

    echo "$OPCOES" | dmenu -i
}
criarArquivos()
{
    # Cria a pasta caso não exista
    test -d "$DIR_CONFIG" || mkdir -p "$DIR_CONFIG"

    # Cria a pasta de downloads
    test -d "$DIR_DOWNLOADS" || mkdir -p "$DIR_DOWNLOADS"

    # Cria o arquivo de links
    test -f "$ARQ_LINKS" || touch "$ARQ_LINKS"
}

#####################################################################
#####################################################################
#####################################################################
#####################################################################

atualizarLinks()
{
    MAIOR_PAGINA=4 # número de páginas do site (em 17-09-2019 haviam 189)

    getLinks $MAIOR_PAGINA

    notify-send Acabado "$(wc -l $ARQ_LINKS | awk '{print $1}') animes salvos em $ARQ_LINKS"
}
# Remove a sintaxe do html deixando apenas a url e o nome
removerHTML()
{
    echo "$1" | sed 's/^.*href="// ; s/" [^"]*"/\t/ ; s/".*// ; s/ /_/g ; s/_Online//' | tr '\t' ' '
}

# Preenche o arquivo ARQ_LINKS
getLinks()
{
    TEMP=$(mktemp)  # Arquivo temporário para guardar links 

    for pagina in $(seq $1)
    do
        LINK="https://animesonline.vip/animes/"
        test $pagina -eq 1 || LINK="$LINK/page/$pagina"

        # Baixa o HTML, procura o nome e o link correspondente e salva num arq temporario
        removerHTML "$(curl -s $LINK | grep '^<a itemp')" >> $TEMP

        # Porcentagem de animes listados
        PORCEN_ANIME=$(calc -p $pagina / $1)
        echo $PORCEN_ANIME
        export PORCEN_ANIME
    done

    # Substitui o arquivo de links anterior pelo arquivo temporário ordenado
    sort -u $TEMP | sed '/^$/ d' > $ARQ_LINKS
    rm $TEMP # e remove-o
}

# Retorna a url da página do anime
selecionarAnime()
{
    dmenu -i -l 10 -p 'Escolha o título: ' < $ARQ_LINKS | awk '{print $1}' 
}

# Retorna a url do episódio
selecionarEpisodio()
{
    # $1 é o link do anime
    test -z "$1" && exit 1 # caso não seja informado o nome

    EPISODIO=$(removerHTML "$(curl -s $1 | grep '^<a href=".*Epis')") # deixa apenas o link e o nome, nessa ordem

    if test -z "$EPISODIO"
    then
        notify-send Erro "Não foi possível abrir o anime"
        exit 1
    fi
    echo "$EPISODIO" | dmenu -i -l 10 -p 'Escolha o episódio: ' | awk '{print $1}' # deixa apenas o link
}

#####################################################################
#####################################################################
#####################################################################
#####################################################################

criarArquivos

for i in $(seq 1)
do
    ESCOLHA="$(menuInicial)"

    case $ESCOLHA in
        "Lista")
            AUX=$(selecionarAnime)
            AUX=$(selecionarEpisodio $AUX)
            menuAcaoEpisodio
            echo $AUX
            ;;
        "Favoritos")
            ;;
        "Downloads")
            ;;
        "Atualizar")
            atualizarLinks
            ;;
        *)
            ;;
    esac
    test "$ESCOLHA" = "Sair" && break
done
